<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<AssemblyName>MegastoreSimulator.GameLibs</AssemblyName>
		<Product>MegastoreSimulator.GameLibs</Product>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>MegastoreSimulator.GameLibs</RootNamespace>
		<InternalsVisibleTo>MegastoreSimulator.GameLibs.Tests</InternalsVisibleTo>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
		<PackageReference Include="UnityEngine.Modules" Version="6000.0.64" IncludeAssets="compile" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp-publicized">
			<HintPath>C:\Users\Miquel\source\repos\MegastoreMod\libs\Assembly-CSharp-publicized.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Megastore Simulator\Megastore Simulator_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime">
		  <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Megastore Simulator\Megastore Simulator_Data\Managed\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Megastore Simulator\Megastore Simulator_Data\Managed\Unity.TextMeshPro.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Megastore Simulator\Megastore Simulator_Data\Managed\UnityEngine.UI.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>
</Project>
